server:
  port: 8080 # app port should always be 8080
  servlet:
    context-path: /user-service/api


spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/ritrovo?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

x-app-token: 3863b160-7cb9-11ed-a1eb-0242ac120002
